name: lint

on: pull_request

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.47
          args: --enable=golint,gosec,prealloc,gocognit
